name: Algarve Surf Lessons
favicon: null
layout_spectrum: 0.08507340145297348
typography_spectrum: 0.6724810861051083
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.06973048625513911
  lightness: 0.13368655182421207
  saturation: 0.7952206246554852
  rhythmicContrast: 0.942351364530623
purpose: []
